import 'package:flutter/cupertino.dart';

/// Flutter icons Bato
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bato
///      fonts:
///       - asset: fonts/Bato.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

class Bato {
  Bato._();

  static const _kFontFam = 'Bato';

  static const IconData looking_for = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData video_games = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ticket = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData sports = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData kitchen = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData food_drinks = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData services = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData jobs = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData womens_fashion = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData mens_fashion = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData beauty_health = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData books = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData kids = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData home_furniture = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData television = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData mobile_phones = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData following = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData user_plus = const IconData(0xf234, fontFamily: _kFontFam);
}
